### PR TITLE
DEVJIRA-5549 :: fix for when the "form_id" key is undefined

### PR DESCRIPTION
**Pull request by w74**
@mthommes are you the lead on reviewing this?

### CODE REVIEW

**Comment by mthommes** [comment]
@cristiangrama is integrations focus lead. I did take a quick look anyway, and it seems okay to me! 👍

**Comment by w74** [comment]
@cristiangrama hey, another one for review

**Comment by rpalladino** [comment]
@w74 you want this merged to master?

**Comment by rpalladino** [comment]
@w74 nevermind me! i forgot we don't have a version branch here...

**Pull request merged**
